### ISSUE TITLE
Append arrow needs css

### ISSUE THREAD

**Issue by apmatthews** [ncstate/wordpress-template#3]
Need to add css for `.nowrap` class that `append_arrow()` function uses.

``` css
.nowrap {
    white-space: nowrap;
}
```
