### ISSUE TITLE
List item styling

### ISSUE THREAD

**Issue by apmatthews** [ncstate/wordpress-template#5]
maybe include this snippet of css to make lists a little more attractive and aligned?

``` scss
ul li {
  margin: 1.2em 0;
  &:before {
    padding-right: 1em;
    margin-left: -2em;
    font-size: 0.6em;
  }
}
```

**Comment by flashadvocate** [comment]
Looks like 3rd level (unordered) lists have a distinct bullet but lack padding, but this seems to be an issue with the NCSU brand bootstrap stylesheet, and not necessarily this theme.

> ![broken_lists](https://cloud.githubusercontent.com/assets/7848492/9770987/2f2449d8-5701-11e5-8820-25c2c153436f.png)

Interestingly enough, the brand guidelines website doesn't even address [3rd level lists](http://brand.ncsu.edu/bootstrap/css/#type-lists), but I'm almost certain someone out there will want this, and then will be frustrated with the result. Since a bullet icon is being added, it should display correctly.

``` css
ul li li li {
    padding-left: 14px;
}
```
